### PR TITLE
Fix frontend dependencies

### PR DESCRIPTION
**Pull request by adrian-lui**
This PR reinstalls all the dependencies to fix several vulnerability issues and reduce the size of the package-lock.json file, so we can submit it to Gitea (which has a file size limit of 1MB). 

These changes will be shuashed with #30, so we won't have an old broken package-lock.json file in git history and can sumit the task to Gitea.

### CODE REVIEW

**Comment by maximihajlov** [comment]
Which dependency uses Python? And why did it work before?

Maybe the proglem is in `npm install`. It's better to use `npm ci` instead as it gurantees persistance of the dependencies 

https://docs.npmjs.com/cli/v10/commands/npm-ci

**Comment by adrian-lui** [comment]
> Which dependency uses Python? And why did it work before?
> 
> Maybe the proglem is in `npm install`. It's better to use `npm ci` instead as it gurantees persistance of the dependencies
> 
> https://docs.npmjs.com/cli/v10/commands/npm-ci

not sure why it worked before. but it happened after I added eslint so it could be that the eslint dep needs python 
`/app/node_modules/@parcel/watcher`
and it doesn't work with just changing it to npm ci.
I suggest that we can keep the issue open but merge this fix already so our buy-02 development progress would not be blocked.

**Comment by maximihajlov** [comment]
It works fine with manually installed python and `npm ci`. I think we should fix issues with dependecies now, because otherwise we won't be able to submit the task (package-lock.json is currenly more than 1MB)

**Comment by adrian-lui** [comment]
> It works fine with manually installed python and `npm ci`. 
I don't understand what you mean

>I think we should fix issues with dependecies now, because otherwise we won't be able to submit the task (package-lock.json is currenly more than 1MB)
I think that's just the size it gets after adding eslint to the project. I'm not sure if I know how to optimize the size of the file just to get it under 1MB. The problem of 1MB do you mean the file size limit of gitea?

**Comment by maximihajlov** [comment]
> I don't understand what you mean

It's possible to build frontend docker image when you manually install python using `apk add`. But maybe there are better options.

> I think that's just the size it gets after adding eslint to the project. I'm not sure if I know how to optimize the size of the file just to get it under 1MB.

Recreating package-lock.json by removing it and calling `npm install` should fix the problem (maybe there're some unnecessary dependencies in it). If not, we can just remove eslint to fit the 1MB file size limit of Gitea.

**Comment by maximihajlov** [comment]
I've fixed the issue with package-lock.json, looks like you installed eslint in a wrong way. I've reinstalled all dependecies from scratch and now we have much less warnings. We also use angular 17, which seem to be completely compatible with the project.

Also looks like your eslint config was broken, I've installed [angular-eslint](https://github.com/angular-eslint/angular-eslint) package using `ng add @angular-eslint/schematics` and now it works well, showing several errors, mosly because of massive usage of `any`:

image

It would be great to fix these errors in `buy-02`.

The `packae-lock.json` file is now just 584K, so we can submit the project to Gitea.

**Review by maximihajlov — APPROVED** [review]
Tested using `docker compose`, works as expected. Also I am able to push it to Gitea

**Comment by maximihajlov** [comment]
The main branch was successfully rebased to squash commits, old revision is 8c04d545fe18e17842b935fd7fc6ea56a1a65718

**Pull request merged**
